name: Generate RSS feed for Counter-Strike 2 updates
on:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Generate RSS Feeds
      id: generate_rss_feeds
      run: python scripts/update-updates-feed.py

    - name: Write RSS feed to files
      run: |
        for rss_feed in ${{ fromJSON(steps.generate_rss_feeds.outputs.rss_feeds) }}; do
          language_code=$(echo $rss_feed | jq -r 'keys[]')
          rss_content=$(echo $rss_feed | jq -r '.[].content')
          echo "$rss_content" > feeds/updates-feed-$language_code.xml
        done

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "📝 Update RSS feeds"
        commit_options: "--no-gpg-sign"
        branch: master
