name: Generate RSS feeds for CS2 updates

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Generate RSS Feeds
      id: generate_rss_feeds
      run: |
        export LC_ALL="en_US.UTF-8"
        export LC_CTYPE="en_US.UTF-8"
        sudo dpkg-reconfigure locales
        python scripts/update-updates-feed.py

    - name: Write RSS feed to files
      run: |
        rss_feeds="${{ steps.generate_rss_feeds.outputs.rss_feeds }}"
        for rss_feed in $(echo "${rss_feeds}" | jq -r '.[]'); do
          _jq() {
            echo "${rss_feed}" | jq -r "${1}"
          }
          
          lang=$(_jq '.language_code')
          rss_content=$(_jq '.content')
          
          echo "$rss_content" > "feeds/updates-feed-${lang}.xml"
        done

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "📝 Update RSS feeds"
        commit_options: "--no-gpg-sign"
        branch: master
